Simulation: Code below is part of process (stage 1) to get random number of date points (within user's selection of start and end date)

In [1]:
import pandas as pd
import random
import time

In [2]:
def str_time_prop(start, end, time_format, prop):
    """Get a time at a proportion of a range of two formatted times.

    start and end should be strings specifying times formatted in the
    given format (strftime-style), giving an interval [start, end].
    prop specifies how a proportion of the interval to be taken after
    start.  The returned time will be in the specified format.
    """

    stime = time.mktime(time.strptime(start, time_format))
    etime = time.mktime(time.strptime(end, time_format))

    ptime = stime + prop * (etime - stime)

    return time.strftime(time_format, time.localtime(ptime))


def random_date(start, end, prop):
    return str_time_prop(start, end, '%m/%d/%Y %I:%M %p', prop)

#for summary page, fit into mobile app:
startdate = '1/1/2008 12:00 AM' #get user input instead of string fr both start & end dates
enddate = '1/30/2008 12:00 AM'

x = random.randint(2,45) #simulate number of readings taken for date range user selected

storevalues = [] #create list

#generate date(s) of random data point 
for i in range(0, x):
    store = random_date(startdate, enddate, random.random()) 
    storevalues.append(store) #append to list

Simulation Stage 2: After the user selects a start and end date, sensor data (4 sensors) will be sent to the application, using random int generator

In [3]:
storevalues

['01/09/2008 11:01 AM',
 '01/07/2008 10:30 PM',
 '01/27/2008 09:33 AM',
 '01/28/2008 07:10 AM',
 '01/04/2008 04:22 AM',
 '01/04/2008 09:59 PM',
 '01/27/2008 12:20 AM',
 '01/23/2008 11:51 PM',
 '01/21/2008 09:04 AM',
 '01/21/2008 01:44 PM',
 '01/10/2008 12:23 AM',
 '01/21/2008 07:55 PM',
 '01/21/2008 04:42 AM',
 '01/08/2008 11:37 AM',
 '01/08/2008 08:28 AM',
 '01/06/2008 10:32 AM',
 '01/24/2008 03:38 AM',
 '01/05/2008 05:39 PM',
 '01/06/2008 12:36 AM',
 '01/21/2008 11:24 PM',
 '01/21/2008 09:23 AM',
 '01/20/2008 03:45 AM',
 '01/06/2008 01:48 PM',
 '01/20/2008 01:55 PM',
 '01/06/2008 08:45 PM',
 '01/04/2008 04:00 PM',
 '01/06/2008 12:14 AM',
 '01/17/2008 09:47 PM',
 '01/17/2008 10:02 AM',
 '01/03/2008 06:28 AM',
 '01/16/2008 02:06 PM']

In [4]:
bplist = [] #create list to store blood pressure values
hrlist = [] #create list to store heart rate values
gluclist = [] #create list to store blood glucose values
emglist = [] #create list to store electromyography values

for x in storevalues:
    #generate for each list(s)
    bp = random.randint(100,125)
    hr = random.randint(90,140)
    gluc = random.randint(100,125)
    emg = random.randint(48,61)
    
    #append to list(s)
    bplist.append(bp) 
    hrlist.append(hr)
    gluclist.append(gluc)
    emglist.append(emg)

In [5]:
bplist,hrlist,gluclist,emglist

([100,
  105,
  119,
  122,
  122,
  105,
  124,
  122,
  108,
  115,
  122,
  108,
  102,
  103,
  103,
  124,
  112,
  102,
  111,
  119,
  113,
  122,
  115,
  106,
  107,
  122,
  125,
  111,
  120,
  102,
  114],
 [99,
  121,
  102,
  129,
  104,
  117,
  137,
  106,
  138,
  132,
  101,
  139,
  139,
  134,
  92,
  124,
  125,
  132,
  101,
  91,
  136,
  123,
  90,
  122,
  117,
  96,
  103,
  122,
  97,
  133,
  105],
 [117,
  113,
  115,
  124,
  109,
  115,
  102,
  117,
  122,
  111,
  103,
  125,
  120,
  103,
  112,
  107,
  100,
  120,
  114,
  104,
  112,
  123,
  118,
  124,
  110,
  118,
  109,
  105,
  125,
  124,
  101],
 [58,
  52,
  53,
  53,
  58,
  53,
  52,
  59,
  58,
  51,
  58,
  58,
  58,
  61,
  49,
  52,
  58,
  51,
  51,
  61,
  50,
  57,
  54,
  61,
  59,
  51,
  53,
  51,
  50,
  50,
  61])

In [83]:
len(bplist)
#len(storevalues)

13

In [88]:
#create a dataframe
pd.DataFrame(list(zip(storevalues,bplist,hrlist,gluclist,emglist)),
              columns=['Datetime','Blood_Pressure','Heart_Rate','Blood_Glucose','EMG'])

               Datetime  Blood_Pressure  Heart_Rate  Blood_Glucose  EMG
0   01/28/2008 01:24 PM             107         133            104   51
1   01/27/2008 10:31 AM             125         127            110   60
2   01/29/2008 03:37 AM             104         101            124   49
3   01/24/2008 07:55 PM             109         122            106   53
4   01/20/2008 11:12 PM             105          91            121   54
5   01/21/2008 11:29 PM             100         105            111   51
6   01/03/2008 06:44 PM             111         139            107   60
7   01/06/2008 09:52 PM             107          90            123   51
8   01/23/2008 12:54 AM             117         103            118   58
9   01/03/2008 11:04 AM             101         137            105   53
10  01/23/2008 04:57 AM             111         112            114   53
11  01/05/2008 08:55 AM             116         118            123   55
12  01/04/2008 12:13 PM             106         125            120   54

In [ ]:
df.to_csv("specifyurfilepath_todownload",index=False)